### ISSUE TITLE
Clang address sanitizer crashes when used with `-DREDIRECT_MALLOC=GC_malloc_uncollectable`

### ISSUE THREAD

**Issue by jeaye** [bdwgc/bdwgc#772]
Hey Ivan! I've found in [jank](https://github.com/jank-lang/jank) that I can't combine ASan and `-DREDIRECT_MALLOC=GC_malloc_uncollectable`. I end up getting a crash prior to the entry point of my program (back trace included below).

I've scanned through the issues and docs and didn't find anything suggesting that these two can or can't be used together, so primarily I'd like to check with you if this is considered a bug or an expected incompatibility.

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555558cb0ca in ___interceptor_pthread_setcancelstate ()
    at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:6811
#2  0x0000555557be3360 in GC_init () at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/misc.c:1066
#3  0x0000555557bdb908 in GC_generic_malloc_inner_small (lb=87, kind=2) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:202
#4  0x0000555557bdc54f in GC_generic_malloc_uncollectable (lb=87, kind=2) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:463
#5  0x0000555557bdc67a in GC_malloc_uncollectable (lb=88) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:506
#6  0x0000555557bdc6b5 in malloc (lb=88) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:553
#7  0x00007ffff7fc6b72 in _dl_exception_create_format () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff7fcdb6c in ?? () from /lib64/ld-linux-x86-64.so.2
#9  0x00007fffee8c3086 in ?? () from /usr/lib/libc.so.6
#10 0x00007fffee7ebe00 in ?? () from /usr/lib/libc.so.6
#11 0x00007ffff7fc4456 in _dl_catch_exception () from /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff7fc45a9 in ?? () from /lib64/ld-linux-x86-64.so.2
#13 0x00007fffee7eb7f3 in ?? () from /usr/lib/libc.so.6
#14 0x00007fffee7ebe9e in dlsym () from /usr/lib/libc.so.6
#15 0x0000555555918334 in GetFuncAddr () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/interception/interception_linux.cpp:42
#16 InterceptFunction () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/interception/interception_linux.cpp:61
#17 0x00005555558f1427 in InitializeCommonInterceptors ()
    at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:10454
#18 0x00005555558ef6df in InitializeAsanInterceptors ()
    at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_interceptors.cpp:803
#19 0x0000555555912373 in AsanInitInternal () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_rtl.cpp:469
#20 0x0000555555912784 in AsanInitFromRtl () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_rtl.cpp:567
#21 __asan_init () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_rtl.cpp:678
#22 0x00007ffff7fc83cf in ?? () from /lib64/ld-linux-x86-64.so.2
#23 0x00007ffff7fe0ba0 in ?? () from /lib64/ld-linux-x86-64.so.2
#24 0x0000000000000003 in ?? ()
#25 0x00007fffffffccf7 in ?? ()
#26 0x00007fffffffcd2d in ?? ()
#27 0x00007fffffffcd3c in ?? ()
#28 0x0000000000000000 in ?? ()
```

## Details
This is on Linux x86_64 and Clang/LLVM 22 (head) on bdwgc's latest master (19a7f495cd7c48cdf6f56c593c6dd57187afa079). I'm building bdwgc alongside my project with the following cmake config:

```cmake
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -w -DREDIRECT_MALLOC=GC_malloc_uncollectable")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -DREDIRECT_MALLOC=GC_malloc_uncollectable")
  set(BUILD_SHARED_LIBS OFF)
  set(CMAKE_CXX_CLANG_TIDY "")
  set(enable_cplusplus ON CACHE BOOL "Enable C++")
  set(build_cord OFF CACHE BOOL "Build cord")
  set(enable_docs OFF CACHE BOOL "Enable docs")
  set(enable_large_config ON CACHE BOOL "Optimize for large heap or root set")
  set(enable_throw_bad_alloc_library ON CACHE BOOL "Enable C++ gctba library build")
  set(enable_gc_debug OFF CACHE BOOL "Support for pointer back-tracing")

  add_subdirectory(third-party/bdwgc EXCLUDE_FROM_ALL)
```

**Comment by ivmai** [comment]
Hello @jeaye,
While nobody reported it, it seems the expected behavior.
I think to fix the issue we need same code in `malloc` (see file `malloc.c`) as in `REDIR_MALLOC_AND_LINUX_THREADS` block of `calloc`. Could you please try it?

**Comment by ivmai** [comment]
E.g. could you please try the following:
```
diff --git a/malloc.c b/malloc.c
index ba6c1edf..b536ea52 100644
--- a/malloc.c
+++ b/malloc.c
@@ -536,26 +536,6 @@ GC_malloc_atomic_uncollectable(size_t lb)
 #    define REDIRECT_MALLOC_F REDIRECT_MALLOC
 #  endif
 
-void *
-malloc(size_t lb)
-{
-  /*
-   * It might help to manually inline the `GC_malloc` call here.
-   * But any decent compiler should reduce the extra procedure call
-   * to at most a jump instruction in this case.
-   */
-#  if defined(SOLARIS) && defined(THREADS) && defined(I386)
-  /*
-   * Thread initialization can call `malloc` before we are ready for.
-   * It is not clear that this is enough to help matters.  The thread
-   * implementation may well call `malloc` at other inopportune times.
-   */
-  if (UNLIKELY(!GC_is_initialized))
-    return sbrk(lb);
-#  endif
-  return (void *)REDIRECT_MALLOC_F(lb);
-}
-
 #  ifdef REDIR_MALLOC_AND_LINUX_THREADS
 #    ifdef HAVE_LIBPTHREAD_SO
 STATIC ptr_t GC_libpthread_start = NULL;
@@ -604,6 +584,40 @@ GC_init_lib_bounds(void)
 }
 #  endif /* REDIR_MALLOC_AND_LINUX_THREADS */
 
+void *
+malloc(size_t lb)
+{
+  /*
+   * It might help to manually inline the `GC_malloc` call here.
+   * But any decent compiler should reduce the extra procedure call
+   * to at most a jump instruction in this case.
+   */
+#  if defined(SOLARIS) && defined(THREADS) && defined(I386)
+  /*
+   * Thread initialization can call `malloc` before we are ready for.
+   * It is not clear that this is enough to help matters.  The thread
+   * implementation may well call `malloc` at other inopportune times.
+   */
+  if (UNLIKELY(!GC_is_initialized))
+    return sbrk(lb);
+#  endif
+#  ifdef REDIR_MALLOC_AND_LINUX_THREADS
+  {
+    ptr_t caller = (ptr_t)__builtin_return_address(0);
+
+    GC_init_lib_bounds();
+    if (ADDR_INSIDE(caller, GC_libld_start, GC_libld_end)
+#    ifdef HAVE_LIBPTHREAD_SO
+        || ADDR_INSIDE(caller, GC_libpthread_start, GC_libpthread_end)
+#    endif
+    ) {
+      return GC_generic_malloc_uncollectable(lb, UNCOLLECTABLE);
+    }
+  }
+#  endif
+  return (void *)REDIRECT_MALLOC_F(lb);
+}
+
 void *
 calloc(size_t n, size_t lb)
 {
```
Note: please check that `REDIR_MALLOC_AND_LINUX_THREADS` is really defined.

**Comment by jeaye** [comment]
Thanks, Ivan! I will give this a go and report back.

**Comment by jeaye** [comment]
Reporting back! Thanks again for taking the time to offer support. :)

So far, the crash still exists. Here's what I've done:

1. Applied your provided patch (on top of 19a7f495cd7c48cdf6f56c593c6dd57187afa079)
2. Added a preprocessor check to ensure `REDIR_MALLOC_AND_LINUX_THREADS` was defined
3. Added `-DREDIR_MALLOC_AND_LINUX_THREADS` since it was not defined
4. Experienced the same crash on start (backtrace below)

Looking at the code, I think the most relevant thing to point out is that `HAVE_LIBPTHREAD_SO` was not defined for me. I tried manually linking in `libpthread.so.0` and providing `-DHAVE_LIBPTHREAD_SO`, but that had no effect. Do you think this is related?

## Backtrace
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555558cc01a in ___interceptor_pthread_setcancelstate ()
    at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:6811
#2  0x0000555557b6d4d8 in GC_init_lib_bounds () at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:557
#3  0x0000555557b6d549 in malloc (lb=88) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:609
#4  0x00007ffff7fc6b72 in _dl_exception_create_format () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7fcdb6c in ?? () from /lib64/ld-linux-x86-64.so.2
#6  0x00007fffeeac3086 in ?? () from /usr/lib/libc.so.6
#7  0x00007fffee9ebe00 in ?? () from /usr/lib/libc.so.6
#8  0x00007ffff7fc4456 in _dl_catch_exception () from /lib64/ld-linux-x86-64.so.2
#9  0x00007ffff7fc45a9 in ?? () from /lib64/ld-linux-x86-64.so.2
#10 0x00007fffee9eb7f3 in ?? () from /usr/lib/libc.so.6
#11 0x00007fffee9ebe9e in dlsym () from /usr/lib/libc.so.6
#12 0x0000555555919284 in GetFuncAddr () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/interception/interception_linux.cpp:42
#13 InterceptFunction () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/interception/interception_linux.cpp:61
#14 0x00005555558f2377 in InitializeCommonInterceptors ()
    at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:10454
#15 0x00005555558f062f in InitializeAsanInterceptors ()
    at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_interceptors.cpp:803
#16 0x00005555559132c3 in AsanInitInternal () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_rtl.cpp:469
#17 0x00005555559136d4 in AsanInitFromRtl () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_rtl.cpp:567
#18 __asan_init () at /home/jeaye/projects/jank/compiler+runtime/build/llvm/compiler-rt/lib/asan/asan_rtl.cpp:678
#19 0x00007ffff7fc83cf in ?? () from /lib64/ld-linux-x86-64.so.2
#20 0x00007ffff7fe0ba0 in ?? () from /lib64/ld-linux-x86-64.so.2
#21 0x0000000000000003 in ?? ()
#22 0x00007fffffffcceb in ?? ()
#23 0x00007fffffffcd21 in ?? ()
#24 0x00007fffffffcd30 in ?? ()
#25 0x0000000000000000 in ?? ()
```

## CMake setup
```cmake
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -w -DREDIRECT_MALLOC=GC_malloc_uncollectable -DREDIR_MALLOC_AND_LINUX_THREADS")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -DREDIRECT_MALLOC=GC_malloc_uncollectable -DREDIR_MALLOC_AND_LINUX_THREADS")
  set(BUILD_SHARED_LIBS OFF)
  set(CMAKE_CXX_CLANG_TIDY "")
  set(enable_cplusplus ON CACHE BOOL "Enable C++")
  set(build_cord OFF CACHE BOOL "Build cord")
  set(enable_docs OFF CACHE BOOL "Enable docs")
  set(enable_threads ON CACHE BOOL "Enable multi-threading support")
  set(enable_large_config ON CACHE BOOL "Optimize for large heap or root set")
  set(enable_throw_bad_alloc_library ON CACHE BOOL "Enable C++ gctba library build")
  set(enable_gc_debug OFF CACHE BOOL "Support for pointer back-tracing")

  add_subdirectory(third-party/bdwgc EXCLUDE_FROM_ALL)
```

**Comment by ivmai** [comment]
> HAVE_LIBPTHREAD_SO was not defined for me

I think it is correct.

**Comment by ivmai** [comment]
```
#2  0x0000555557b6d4d8 in GC_init_lib_bounds () at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:557
#3  0x0000555557b6d549 in malloc (lb=88) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:609
#4  0x00007ffff7fc6b72 in _dl_exception_create_format () from /lib64/ld-linux-x86-64.so.2
```
The problem here is that we should call GC_init_lib_bounds earlier than `InitializeCommonInterceptors`.

I wonder if `GC_wrap_dlopen` is called before you get the crash?

**Comment by ivmai** [comment]
>  I think to fix the issue we need same code in malloc (see file malloc.c) as in REDIR_MALLOC_AND_LINUX_THREADS block of calloc. Could you please try it?

This was wrong advice, because GC_init cannot be called during InitializeAsanInterceptors(). At the same time we cannot call GC_init before it.

The only advice here is to redirect to `sbrk` if `GC_is_initialized` is false. The client code is responsible to call GC_init explicitly in this case.

**Comment by jeaye** [comment]
Thank you for the follow up! Other items have been pushed to the front of my queue, but I will report back when I can finally look into this again.

**Comment by ivmai** [comment]
Please also note that a more serios bug was found (and no solution proposed yet) recently if modern ASan is used: #789

**Comment by ivmai** [comment]
Please note that after b74fddc, redirecton to uncollectable malloc is configured like:
`./configure --enable-redirect-malloc --enable-uncollectable-redirection`

**Comment by jeaye** [comment]
> Please note that after [b74fddc](https://github.com/bdwgc/bdwgc/commit/b74fddcfa750efbd00e9a20bfee43e343a85792f), redirecton to uncollectable malloc is configured like: `./configure --enable-redirect-malloc --enable-uncollectable-redirection`

Is this changed for folks using CMake as well? That's how I'm consuming bdwgc.

**Comment by jeaye** [comment]
Ah, I see the details in this commit (different from what you linked): https://github.com/bdwgc/bdwgc/commit/32b74811147649efab0944b2762fc3300074d25e

Thanks for the heads up, Ivan!

**Comment by ivmai** [comment]
I've reproduced the original issue:
Source: master (f7b7bc8c89)
Host: Ubuntu 24/x86_64
Compiler: clang 18.1.3
Commands (both single- and multi-threaded):
1. `clang -I include -O0 -g -fsanitize=address -D REDIRECT_MALLOC_UNCOLLECTABLE tests/gctest.c extra/gc.c`
2. `clang -I include -I libatomic_ops/src -O0 -g -fsanitize=address -D REDIRECT_MALLOC_UNCOLLECTABLE -D GC_THREADS tests/gctest.c extra/gc.c -ldl -lpthread`

gdb stack trace:
```
#0  0x00005555556703c8 in AO_load (addr=0x5555560c07e8 <GC_arrays+328>)
    at libatomic_ops/src/atomic_ops/sysdeps/gcc/generic-small.h:505
#1  0x00005555556784eb in GC_generic_malloc_uncollectable (lb=72, kind=2)
    at extra/../malloc.c:444
#2  0x000055555567207a in GC_malloc_uncollectable (lb=72)
    at extra/../malloc.c:504
#3  0x0000555555678e95 in malloc (lb=72) at extra/../malloc.c:554
#4  0x00007ffff7fc8db2 in malloc (size=72) at ../include/rtld-malloc.h:56
#5  __GI__dl_exception_create_format (
    exception=exception@entry=0x7fffffffddd0,
    objname=0x7fffffffe4ed "/home/i.maidanski/opensource/gc/a.out",
    fmt=fmt@entry=0x7ffff7ff3039 "undefined symbol: %s%s%s")
    at ./elf/dl-exception.c:157
#6  0x00007ffff7fd0642 in _dl_lookup_symbol_x (
    undef_name=0x5555556a8443 "__isoc99_printf", undef_map=0x7ffff7ffe2e0,
    ref=0x7fffffffde48, symbol_scope=<optimized out>, version=<optimized out>,
    type_class=0, flags=2, skip_map=0x7ffff7ffe2e0) at ./elf/dl-lookup.c:809
#7  0x00007ffff7d8524d in do_sym (flags=2, vers=0x0,
    who=0x555555634f88 <__interception::InterceptFunction(char const*, unsigned long*, unsigned long, unsigned long)+40>,
    name=0x5555556a8443 "__isoc99_printf", handle=<optimized out>)
    at ./elf/dl-sym.c:146
#8  _dl_sym (handle=<optimized out>, name=0x5555556a8443 "__isoc99_printf",
    who=0x555555634f88 <__interception::InterceptFunction(char const*, unsigned long*, unsigned long, unsigned long)+40>) at ./elf/dl-sym.c:195
#9  0x00007ffff7c982b0 in dlsym_doit (a=a@entry=0x7fffffffe0f0)
    at ./dlfcn/dlsym.c:40
#10 0x00007ffff7fc651c in __GI__dl_catch_exception (
    exception=exception@entry=0x7fffffffe030,
    operate=0x7ffff7c98290 <dlsym_doit>, args=0x7fffffffe0f0)
    at ./elf/dl-catch.c:237
#11 0x00007ffff7fc6669 in _dl_catch_error (objname=0x7fffffffe098,
    errstring=0x7fffffffe0a0, mallocedp=0x7fffffffe097,
    operate=<optimized out>, args=<optimized out>) at ./elf/dl-catch.c:256
#12 0x00007ffff7c97c83 in _dlerror_run (
    operate=operate@entry=0x7ffff7c98290 <dlsym_doit>,
    args=args@entry=0x7fffffffe0f0) at ./dlfcn/dlerror.c:138
#13 0x00007ffff7c98344 in dlsym_implementation (dl_caller=<optimized out>,
    name=<optimized out>, handle=<optimized out>) at ./dlfcn/dlsym.c:54
#14 ___dlsym (handle=<optimized out>, name=<optimized out>)
    at ./dlfcn/dlsym.c:68
#15 0x0000555555634f88 in __interception::InterceptFunction(char const*, unsigned long*, unsigned long, unsigned long) ()
#16 0x0000555555610767 in InitializeCommonInterceptors() ()
#17 0x000055555560e613 in __asan::InitializeAsanInterceptors() ()
#18 0x000055555562f30b in __asan::AsanInitInternal() ()
#19 0x000055555562f6c8 in __asan_init ()
#20 0x00007ffff7fca873 in _dl_init (main_map=0x7ffff7ffe2e0, argc=1,
    argv=0x7fffffffe248, env=0x7fffffffe258) at ./elf/dl-init.c:106
#21 0x00007ffff7fe45a0 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#22 0x0000000000000001 in ?? ()
```

**Comment by jeaye** [comment]
Oh, nice work, Ivan! Sorry I've been quiet on this one; I'm still very interested in bdwgc + asan support, but other items have taken precedence.

**Comment by ivmai** [comment]
Should be fixed now in master branch, please test it.

**Comment by jeaye** [comment]
I will test this in the morning and report back! Thank you, Ivan!

**Comment by ivmai** [comment]
However I  do not like the applied solution (7623ae2) because it has too many implications (system code should not call realloc, client should call GC init explicitly).

**Comment by jeaye** [comment]
I've tested this in jank today and I still get the same crash:

```
#0  0x0000000000000000 in ?? ()
#1  0x0000555557a711cd in GC_init () at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/misc.c:1054
#2  0x0000555557a68d78 in GC_generic_malloc_inner_small (lb=95, kind=2) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:202
#3  0x0000555557a699ff in GC_generic_malloc_uncollectable (lb=95, kind=2) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:463
#4  0x0000555557a69b3a in GC_malloc_uncollectable (lb=96) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:504
#5  0x0000555557a69b95 in malloc (lb=96) at /home/jeaye/projects/jank/compiler+runtime/third-party/bdwgc/malloc.c:554
#6  0x00007ffff7fc9da2 in _dl_exception_create_format () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/ld-linux-x86-64.so.2
#7  0x00007ffff7fd014c in _dl_lookup_symbol_x () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/ld-linux-x86-64.so.2
#8  0x00007fffe7b7dfe5 in do_sym () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/libc.so.6
#9  0x00007fffe7a97d30 in dlsym_doit () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/libc.so.6
#10 0x00007ffff7fc7566 in _dl_catch_exception () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/ld-linux-x86-64.so.2
#11 0x00007ffff7fc76b9 in _dl_catch_error () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/ld-linux-x86-64.so.2
#12 0x00007fffe7a97683 in _dlerror_run () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/libc.so.6
#13 0x00007fffe7a97dde in dlsym@GLIBC_2.2.5 () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/libc.so.6
#14 0x0000555555930f35 in __interception::InterceptFunction(char const*, unsigned long*, unsigned long, unsigned long) ()
#15 0x0000555555843d0a in InitializeCommonInterceptors() ()
#16 0x000055555591731f in __asan::InitializeAsanInterceptors() ()
#17 0x000055555592b650 in __asan::AsanInitInternal() [clone .part.0] ()
#18 0x000055555592b9a5 in __asan_init ()
#19 0x00007ffff7fca8af in _dl_init () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/ld-linux-x86-64.so.2
#20 0x00007ffff7fe3e60 in _dl_start_user () from /nix/store/j193mfi0f921y0kfs8vjc1znnr45ispv-glibc-2.40-66/lib/ld-linux-x86-64.so.2
#21 0x0000000000000003 in ?? ()
#22 0x00007fffffff75c2 in ?? ()
#23 0x00007fffffff7600 in ?? ()
#24 0x00007fffffff760f in ?? ()
#25 0x0000000000000000 in ?? ()
```

I'm on BDWGC ea7255d41e2a4cec49fef4320eb426542d193249 with this CMake setup:

```
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -w")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w")
  set(CMAKE_CXX_CLANG_TIDY "")
  set(GC_BUILD_SHARED_LIBS OFF)
  set(enable_redirect_malloc ON CACHE BOOL "Redirect malloc and friends to collector routines")
  set(enable_uncollectable_redirection ON CACHE BOOL "Redirect to uncollectible malloc instead of garbage-collected one")
  set(enable_cplusplus ON CACHE BOOL "Enable C++")
  set(build_cord OFF CACHE BOOL "Build cord")
  set(enable_docs OFF CACHE BOOL "Enable docs")
  set(enable_threads ON CACHE BOOL "Enable multi-threading support")
  set(enable_large_config ON CACHE BOOL "Optimize for large heap or root set")
  set(enable_throw_bad_alloc_library ON CACHE BOOL "Enable C++ gctba library build")
  set(enable_gc_debug OFF CACHE BOOL "Support for pointer back-tracing")

  add_subdirectory(third-party/bdwgc EXCLUDE_FROM_ALL)
```

----
However, as I just mentioned in #829, I have now disabled redirection for jank, since it's no longer needed. So this issue is no longer a problem for jank, but it may be something you're still interested in supporting.

**Comment by ivmai** [comment]
Similar issue when redirecting to `GC_malloc`.
Source: master (41470af7f)
Build: https://github.com/ivmai/bdwgc-fork/actions/runs/21492473338/job/61918360501
Host: Debian/x86_64
How to build: `./configure --disable-shared --enable-gc-assertions --enable-redirect-malloc && make check CFLAGS_EXTRA="-O0 -fsanitize=address"`

Output:
```
AddressSanitizer: SEGV on unknown address 0x000000002010 (pc 0x56405017c29c bp 0x7ffcc872b770 sp 0x7ffcc872b740 T0)
==1972187==The signal is caused by a READ memory access.
    #0 0x56405017c29c in GC_find_header bdwgc/headers.c:37
    #1 0x56405017f565 in GC_realloc bdwgc/mallocx.c:103
    #2 0x56405017fae7 in realloc bdwgc/mallocx.c:223
    #3 0x7f4bcdb7836b in __vasprintf_internal libio/vasprintf.c:79
    #4 0x7f4bcdb53095 in ___asprintf stdio-common/asprintf.c:31
    #5 0x7f4bcdcee988 in __dlerror dlfcn/dlerror.c:102
    #6 0x7f4bcddc9697 in AsanInitInternal ../../../../src/libsanitizer/asan/asan_rtl.cpp:521
    #7 0x7f4bce70713d in _dl_init elf/dl-init.c:104
    #8 0x7f4bce6f80c9  (/lib64/ld-linux-x86-64.so.2+0x10c9)
```
